# Generated by Django 6.0.3 on 2026-03-30 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysis',
            old_name='about',
            new_name='summary',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='type',
        ),
        migrations.AddField(
            model_name='analysis',
            name='period_type',
            field=models.CharField(choices=[('weekly', '주간'), ('monthly', '월간')], default='monthly', max_length=10),
        ),
    ]
